# Generated by Django 4.1.4 on 2023-01-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='min_bid',
        ),
    ]
