# Generated by Django 4.1.4 on 2023-01-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_min_bid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watch_list',
            unique_together={('user_id', 'listing_id')},
        ),
    ]
